using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.CodeDom.Compiler;
using System.IO;
using System.Linq;
using System.Threading;
using Trarizon.Bangumi.Api.Internal.Generators.Utilities;
using Trarizon.Bangumi.Api.Internal.Generators.Utilities.Collections;

namespace Trarizon.Bangumi.Api.Internal.Generators;
[Generator(LanguageNames.CSharp)]
internal sealed class EnumPropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddEmbeddedAttributeDefinition();
            context.AddSource("JsonStringEnum.g.i.cs", """
                #nullable enable
                #pragma warning disable CS9113
                
                namespace Trarizon.Bangumi.Api.Internal.Attributes
                {
                    /// <summary>
                    /// The method is used to generate 2 methods `FromJsonStringValue` and `ToJsonStringValue`
                    /// to convert a string to and from the enum.
                    /// </summary>
                    [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                    [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
                    internal sealed class JsonStringEnumAttribute(string? name = null) : global::System.Attribute;
                    
                    /// <summary>
                    /// The method is used to generate `ToQueryStringValue` to convert the enum to a string use in query string.
                    /// </summary>
                    [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                    [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
                    internal sealed class QueryStringEnumAttribute(string? name = null) : global::System.Attribute;
                }
                """);
        });


        var transform = (GeneratorAttributeSyntaxContext context, CancellationToken _) =>
        {
            var syntax = (EnumDeclarationSyntax)context.TargetNode;
            var symbol = (INamedTypeSymbol)context.TargetSymbol;

            var typeIden = (string?)context.Attributes[0].ConstructorArguments[0].Value;

            var fields = symbol.GetMembers()
                .OfType<IFieldSymbol>()
                .Select(f =>
                {
                    string? str;
                    str = Utils.ToCamelCase(f.Name);
                    return (val: f.Name, str);
                });

            return (
                filename: symbol.ToDisplayString(),
                ns: symbol.ContainingNamespace,
                typeiden: typeIden ?? symbol.Name,
                typename: symbol.Name,
                typefullname: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                fields: fields.ToSequenceEquatableImmutableArray());
        };

        var jsonSrc = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Trarizon.Bangumi.Api.Internal.Attributes.JsonStringEnumAttribute",
            (node, _) => node is EnumDeclarationSyntax,
            transform);

        context.RegisterSourceOutput(jsonSrc, (context, source) =>
        {
            var (fn, ns, typeiden, typename, typefname, fields) = source;
            try {
                using var sw = new StringWriter();
                using var writer = new IndentedTextWriter(sw);

                writer.WriteLine("// <auto-generated />");
                writer.WriteLine("#nullable enable");
                writer.WriteLine();

                writer.WriteLine($"namespace {ns}");
                writer.WriteLine('{');
                writer.Indent++;

                writer.WriteLine($"static partial class {typeiden}Extensions");
                writer.WriteLine('{');
                writer.Indent++;
                writer.WriteLine($"extension({typefname} value)");
                writer.WriteLine('{');
                writer.Indent++;

                writer.WriteLine($"internal static {typefname} FromJsonStringValue(string str) => str switch");
                writer.WriteLine('{');
                writer.Indent++;
                foreach (var (val, str) in fields.Array) {
                    if (str is not null)
                        writer.WriteLine($"\"{str}\" => {typefname}.{val},");
                    else
                        writer.WriteLine($"null => {typefname}.{val},");
                }
                writer.WriteLine($"_ => global::Trarizon.Bangumi.Api.Utilities.Throws.ThrowUnknownEnumCastValue<{typefname}>(str),");
                writer.Indent--;
                writer.WriteLine("};");
                writer.WriteLine();

                writer.WriteLine($"internal string ToJsonStringValue() => value switch");
                writer.WriteLine('{');
                writer.Indent++;
                foreach (var (val, str) in fields.Array) {
                    writer.WriteLine($"{typefname}.{val} => \"{str}\",");
                }
                writer.WriteLine("_ => global::Trarizon.Bangumi.Api.Utilities.Throws.ThrowUnknownEnumValue<string>(value),");
                writer.Indent--;
                writer.WriteLine("};");

                writer.Indent--;
                writer.WriteLine('}');
                writer.Indent--;
                writer.WriteLine('}');

                // namespace
                writer.Indent--;
                writer.WriteLine('}');

                // end Extensions

                context.AddSource($"{fn}.g.cs", sw.ToString());
            }
            catch (Exception ex) {
                context.AddSource($"{fn}.g.e.cs", $"""
                    /*
                    {ex.Message}

                    {ex.StackTrace}
                    */
                    """);
            }
        });

        var querySrc = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Trarizon.Bangumi.Api.Internal.Attributes.QueryStringEnumAttribute",
            (node, _) => node is EnumDeclarationSyntax,
            transform);

        context.RegisterSourceOutput(querySrc, (context, source) =>
        {
            var (fn, ns, typeiden, typename, typefname, fields) = source;
            try {
                using var sw = new StringWriter();
                using var writer = new IndentedTextWriter(sw);

                writer.WriteLine("// <auto-generated />");
                writer.WriteLine("#nullable enable");
                writer.WriteLine();

                writer.WriteLine($"namespace {ns}");
                writer.WriteLine('{');
                writer.Indent++;
                writer.WriteLine($"static partial class {typeiden}Extensions");
                writer.WriteLine('{');
                writer.Indent++;

                writer.WriteLine($"internal static string ToQueryString(this {typefname} value) => value switch");
                writer.WriteLine('{');
                writer.Indent++;
                foreach (var (val, str) in fields.Array) {
                    writer.WriteLine($"{typefname}.{val} => \"{str}\",");
                }
                writer.WriteLine("_ => global::Trarizon.Bangumi.Api.Utilities.Throws.ThrowUnknownEnumValue<string>(value),");
                writer.Indent--;
                writer.WriteLine("};");

                writer.Indent--;
                writer.WriteLine('}');
                writer.Indent--;
                writer.WriteLine('}');

                context.AddSource($"{fn}.g.cs", sw.ToString());
            }
            catch (Exception ex) {
                context.AddSource($"{fn}.g.e.cs", $"""
                    /*
                    {ex.Message}

                    {ex.StackTrace}
                    */
                    """);
            }
        });
    }
}